#!/bin/bash
cat access.log | grep -E "[A-Z]{3,4} .+(HTTP)" | awk '{print  $1 "\t" $9 "\t" $10 "\t" $7}'| awk '$2 ~/4../{print $0}' |
 awk '$0 = NR" "$0' | sort -k4rn -k1n | sed -r 's/\?.+//' | head -n 5 | awk '{$1=""; print $0}'
