version: '2.1'

networks:
  final_network:
    external:
      name: final_project

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: mysql
    networks:
      - final_network
    volumes:
      - .\mysql\init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', '-uroot', '-ppass', 'ping', '-h', 'mysql']
      timeout: 1s
      retries: 30

  myapp:
    image: myapp:latest
    networks:
      - final_network
    volumes:
      - .\config.py:/tmp/cfg
    entrypoint: '/app/myapp --config=/tmp/cfg'
    container_name: myapp
    ports:
      - '8080:8080'
    links:
      - mysql
    environment:
      - PATH_TO_CONFIG=${PATH_TO_CONFIG}
      - DOCKER_PATH_TO_CONFIG=${DOCKER_PATH_TO_CONFIG}
      - APP_PORT=${APP_PORT}
      - MYSQL_CONTAINER_NAME=${MYSQL_HOST}
      - VK_API_CONTAINER_NAME=${VK_API_HOST}
      - VK_API_HOSTNAME=${VK_API_HOST}
    healthcheck:
      test: curl -sS http://localhost:8080/status || echo 1
      timeout: 1s
      retries: 30
    depends_on:
      mysql:
        condition: service_healthy